import {Inter} from "next/font/google"
import "@/styles/globals.css" 
import { Provider } from "@/components/provider"

const inter = Inter({subsets: ["latin"]})

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
   <html lang="en">
     <body className="{inter.className">
       <Provider>{children}</Provider>
     </body>
   </html>
 );
}
